api/urls.py
from django.conf.urls import url

import djapi as api
from . import views


urlpatterns = [
    url(r'^series/$', views.series),
    url(r'^series/(\w+)/$', views.series_detail),
    url(r'^series/(\w+)/samples/$', views.series_samples),

    url(r'^platforms/$', views.platforms),
    url(r'^platforms/(\w+)/$', views.platform_detail),
    url(r'^platforms/(\w+)/probes/$', views.platform_probes),

    url(r'^tags/$', api.route(get=views.tags, post=views.tag_create)),
    # url(r'^tags/form/$', views.tag_create),
    url(r'^tags/(\d+)/$', views.tag_detail),

    url(r'^analysis/$', api.get_post(views.analysis_list, views.analysis_create), name='analysis'),
    url(r'^analysis/form/$', api.show_form(form=views.AnalysisForm, view='analysis')),
    url(r'^analysis/(\d+)/$', views.analysis_detail),
    url(r'^analysis/(\d+)/results/$', views.analysis_results),

    url(r'^annotations/$', api.get_post(views.annotations, views.annotate), name='annotations'),
    url(r'^annotations/form/$', api.show_form(form=views.AnnotateForm, view='annotations')),
    url(r'^annotations/(\d+)/$', views.annotation_detail),
    url(r'^annotations/(\d+)/samples/$', views.annotation_samples),
]

stargeo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from registration.backends.hmac.views import RegistrationView

from core.forms import PasswordResetForm, MyRegistrationForm, MyAuthenticationForm
from api.routers import router
from api.viewsets import SwaggerSchemaView

import django.contrib.auth.views
import core.views
import tags.views
import tags.annotate_views
import tags.review_views
import tags.user_views
import analysis.views
import api.views
import oauth2access


urlpatterns = [
    url(r'^accounts/login/$', django.contrib.auth.views.login,
        {'authentication_form': MyAuthenticationForm}, name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout,
        {'next_page': '/'}),
    url(r'^accounts/register/$',
        RegistrationView.as_view(form_class=MyRegistrationForm),
        name='registration_register'),
    url(r'^accounts/reactivate/$', core.views.reactivate, name='reactivate'),
    url(r'^accounts/reactivate_sent/$', core.views.reactivate_sent, name='reactivate_sent'),
    url(r'^accounts/password_reset/$', django.contrib.auth.views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.txt',
         'password_reset_form': PasswordResetForm},
        name='password_reset'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),

    url(r'^$', core.views.dashboard, name='dashboard'),

    url(r'^search/$', tags.views.search, name='search'),
    url(r'^tags/$', tags.views.tag_control, name='tag_control'),
    url(r'^tags/create/$', tags.views.create_tag, name='tag_create'),
    url(r'^tags/(\d+)/$', tags.views.tag, name='tag'),
    url(r'^tags/(\d+)/delete/$', tags.views.delete_tag, name='tag_delete'),

    url(r'^annotate/$', tags.annotate_views.annotate, name='annotate'),
    url(r'^validate/$', tags.annotate_views.validate, name='validate'),
    url(r'^on_demand_validate/$', tags.annotate_views.on_demand_validate,
        name='on_demand_validate'),
    url(r'^on_demand_result/(\d+)/$', tags.annotate_views.on_demand_result,
        name='on_demand_result'),
    url(r'^competence/$', tags.annotate_views.competence, name='competence'),

    # Annotations reviews and snapshots
    url(r'^annotations/$', tags.review_views.series_annotations,
        name='series_annotations'),
    url(r'^annotations/(\d+)/samples/$', tags.review_views.sample_annotations,
        name='sample_annotations'),
    url(r'^annotations/ignore/(\d+)/$', tags.review_views.ignore, name='ignore_validation'),
    url(r'^snapshot/$', tags.review_views.snapshot, name='snapshot'),
    url(r'^snapshots/review/$', tags.review_views.review_snapshot, name='review_snapshot'),
    url(r'^snapshots/(\d+)/$', tags.review_views.snapshot_detail, name='snapshot_detail'),
    url(r'^snapshots/(\d+)\.(\w+)', tags.review_views.snapshot_file, name='snapshot_file'),
    url(r'^snapshots/(\d+)/to_zenodo/$', tags.review_views.upload_to_zenodo, name='to_zenodo'),
    url(r'^auth_zenodo/$', tags.review_views.authorize_zenodo, name='auth_zenodo'),
    url(r'^my/snapshots/$', tags.review_views.my_snapshots, name='my_snapshots'),

    # Analysis
    url(r'^analysis/$', analysis.views.index, name='analysis'),
    url(r'^analysis/create/$', analysis.views.create, name='analysis_create'),
    url(r'^analysis/(\d+)/$', analysis.views.detail, name='analysis_results'),
    url(r'^analysis/(\d+)/([^/]+).json$', analysis.views.forest_data,
        name='analysis_forest_data'),
    url(r'^analysis/(\d+)/([^/]+).png$', analysis.views.forest, name='analysis_forest'),
    url(r'^analysis/(\d+)/export/$', analysis.views.export, name='analysis_export'),
    url(r'^analysis/(\d+)/frame/$', analysis.views.frame, name='analysis_frame'),
    url(r'^analysis/(\d+)/log/$', analysis.views.log, name='analysis_log'),
    url(r'^analysis/(\d+)/rerun/$', analysis.views.rerun, name='analysis_rerun'),
    url(r'^analysis/(\d+)/delete/$', analysis.views.delete, name='analysis_delete'),

    # Admin/profile areas
    url(r'^users/$', tags.user_views.stats, name='stats'),
    url(r'^accounting/$', tags.user_views.accounting, name='accounting'),
    url(r'^account_info/$', tags.user_views.account_info, name='account_info'),
    url(r'^redeem/$', tags.user_views.redeem, name='redeem'),
    url(r'^pay/$', tags.user_views.pay, name='pay'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(router.urls)),
    url(r'^api/v2/', include('api.urls')),
    url(r'^api_docs/$', api.views.docs),
    url(r'^api_docs/v1/$', SwaggerSchemaView.as_view()),
    url(r'^docs/$', RedirectView.as_view(url='/api_docs/', permanent=True)),

    url(r'^stats/$', core.views.stats, name='statistics'),

    url(r'^oauth2callback/', oauth2access.callback, name='oauth2callback')
]


from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

# from djapi import make_page_not_found
# handler404 = make_page_not_found('/api')

tags/models.py
import re
from collections import OrderedDict
from decimal import Decimal
import json
from funcy import cat, walk_keys

from django.db import models
from django.db.models import Count
from django.utils import timezone

from handy.models import JSONField
from django_pandas.managers import DataFrameManager
from s3field import S3MultiField


ANNOTATION_REWARD = Decimal('0.05')
VALIDATION_REWARD = Decimal('0.03')


class Tag(models.Model):
    tag_name = models.CharField(max_length=512)
    description = models.CharField(max_length=512, blank=True)

    ontology_id = models.CharField(max_length=127, blank=True)
    concept_full_id = models.CharField(max_length=512, blank=True)
    concept_name = models.CharField(max_length=512, blank=True)

    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    created_by = models.ForeignKey('core.User', db_column='created_by', blank=True, null=True,
                                   related_name='tags')
    modified_on = models.DateTimeField(blank=True, null=True, auto_now=True)
    modified_by = models.ForeignKey('core.User', db_column='modified_by', blank=True, null=True,
                                    related_name='+')

    class Meta:
        db_table = 'tag'

    def __str__(self):
        return self.tag_name

    def get_stats(self):
        def annotate(qs):
            return list(qs.values_list('annotation').annotate(Count('id')).order_by('annotation'))

        return {
            'annotations': annotate(SampleTag.objects.filter(series_tag__tag=self)),
            'validations': annotate(SampleValidation.objects.filter(serie_validation__tag=self)),
            'canonical': annotate(SampleAnnotation.objects.filter(series_annotation__tag=self)),
        }

    def remap_annotations(self, old, new):
        """
        When boolean tag changes its name we need to update all annotations.
        """
        if old != new:
            RawSampleAnnotation.objects.filter(series_annotation__tag=self, annotation=old) \
                               .update(annotation=new)
            SampleAnnotation.objects.filter(series_annotation__tag=self, annotation=old) \
                            .update(annotation=new)

    def remap_refs(self, new_pk):
        """
        Remap any references to this tag to other one. Used in tag merge.
        """
        RawSeriesAnnotation.objects.filter(tag=self).update(tag=new_pk)
        SeriesAnnotation.objects.filter(tag=self).update(tag=new_pk)


class SeriesTag(models.Model):
    series = models.ForeignKey('legacy.Series', blank=True, null=True)
    platform = models.ForeignKey('legacy.Platform', blank=True, null=True)
    tag = models.ForeignKey(Tag, blank=True, null=True)
    header = models.CharField(max_length=512, blank=True)
    regex = models.CharField(max_length=512, blank=True)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    created_by = models.ForeignKey('core.User', db_column='created_by', blank=True, null=True,
                                   related_name='+')
    modified_on = models.DateTimeField(blank=True, null=True, auto_now=True)
    modified_by = models.ForeignKey('core.User', db_column='modified_by', blank=True, null=True,
                                    related_name='+')

    # Number of validation, which led to first agreement
    # (with whatever previous one, not necessarily initial)
    agreed = models.IntegerField(blank=True, null=True)
    fleiss_kappa = models.FloatField(blank=True, null=True)
    note = models.TextField(blank=True, default='')
    from_api = models.BooleanField(default=False)

    class Meta:
        db_table = 'series_tag'


class SampleTag(models.Model):
    sample = models.ForeignKey('legacy.Sample', blank=True, null=True)
    series_tag = models.ForeignKey(SeriesTag, blank=True, null=True, related_name='sample_tags')
    annotation = models.TextField(blank=True, default='')
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    created_by = models.ForeignKey('core.User', db_column='created_by', blank=True, null=True,
                                   related_name='sample_annotations')
    modified_on = models.DateTimeField(blank=True, null=True, auto_now=True)
    modified_by = models.ForeignKey('core.User', db_column='modified_by', blank=True, null=True,
                                    related_name='+')

    objects = DataFrameManager()

    class Meta:
        db_table = 'sample_tag'

###

class UserStats(models.Model):
    user = models.OneToOneField('core.User', primary_key=True, related_name='stats')

    serie_tags = models.IntegerField(default=0)
    sample_tags = models.IntegerField(default=0)
    serie_validations = models.IntegerField(default=0)
    sample_validations = models.IntegerField(default=0)
    serie_validations_concordant = models.IntegerField(default=0)
    sample_validations_concordant = models.IntegerField(default=0)

    # Purely stats
    earned_sample_annotations = models.IntegerField(default=0)
    earned_sample_validations = models.IntegerField(default=0)

    # Used for payments
    earned = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    payed = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    @property
    def serie_validation_concordancy(self):
        if self.serie_validations:
            return float(self.serie_validations_concordant) / self.serie_validations
        else:
            return None

    @property
    def unpayed(self):
        return self.earned - self.payed

    def earn_annotations(self, count):
        self.earned_sample_annotations += count
        self.earned += ANNOTATION_REWARD * count

    def earn_validations(self, count):
        self.earned_sample_validations += count
        self.earned += VALIDATION_REWARD * count


class PaymentState(object):
    PENDING, DONE, FAILED = 1, 2, 3
    choices = (
        (1, 'pending'),
        (2, 'done'),
        (3, 'failed'),
    )


class Payment(models.Model):
    receiver = models.ForeignKey('core.User', related_name='payments')
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    method = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('core.User')
    state = models.IntegerField(choices=PaymentState.choices)
    extra = JSONField(default={})

    @property
    def failed(self):
        return self.state == PaymentState.FAILED


class ValidationJob(models.Model):
    annotation = models.ForeignKey('SeriesAnnotation', null=True)
    series_tag = models.ForeignKey(SeriesTag, null=True, on_delete=models.CASCADE)  # TODO: drop
    locked_on = models.DateTimeField(blank=True, null=True)
    locked_by = models.ForeignKey('core.User', blank=True, null=True)
    # generation = models.IntegerField(default=1)
    priority = models.FloatField(default=0)

    class Meta:
        db_table = 'validation_job'


class SerieValidation(models.Model):
    series_tag = models.ForeignKey(SeriesTag, related_name='validations',
                                   blank=True, null=True, on_delete=models.SET_NULL)
    series = models.ForeignKey('legacy.Series', related_name='validations')
    platform = models.ForeignKey('legacy.Platform', related_name='validations')
    tag = models.ForeignKey(Tag, related_name='validations')
    column = models.CharField(max_length=512, blank=True)
    regex = models.CharField(max_length=512, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('core.User')
    on_demand = models.BooleanField(default=False)
    ignored = models.BooleanField(default=False)
    by_incompetent = models.BooleanField(default=False)
    note = models.TextField(blank=True, default='')
    from_api = models.BooleanField(default=False)

    # Calculated fields
    samples_total = models.IntegerField(null=True)
    samples_concordant = models.IntegerField(null=True)
    annotation_kappa = models.FloatField(blank=True, null=True)
    best_kappa = models.FloatField(blank=True, null=True)
    agrees_with = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        db_table = 'series_validation'

    # TODO: get rid of samples_concordant and concordant field in sample validations
    @property
    def concordant(self):
        return self.samples_concordant == self.samples_total

    @property
    def same_as_canonical(self):
        samples = dict(self.sample_validations.values_list('sample_id', 'annotation'))
        canonical_samples = dict(self.series_tag.canonical.sample_annotations
                                     .values_list('sample_id', 'annotation'))
        return samples == canonical_samples


class SampleValidation(models.Model):
    sample = models.ForeignKey('legacy.Sample', blank=True, null=True)
    serie_validation = models.ForeignKey(SerieValidation, related_name='sample_validations')
    annotation = models.TextField(blank=True, default='')
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('core.User')

    # Calculated field
    concordant = models.NullBooleanField(null=True)

    class Meta:
        db_table = 'sample_validation'


class RawSeriesAnnotation(models.Model):
    canonical = models.ForeignKey('tags.SeriesAnnotation', related_name='raw_annotations')
    series = models.ForeignKey('legacy.Series')
    platform = models.ForeignKey('legacy.Platform')
    tag = models.ForeignKey(Tag)
    column = models.CharField(max_length=512, blank=True)
    regex = models.CharField(max_length=512, blank=True)
    created_by = models.ForeignKey('core.User', related_name='+')
    created_on = models.DateTimeField(default=timezone.now)

templates/users/accounting.j2
{% extends "base.j2" %}

{% block content %}
<h2>Account Info</h2>
<p id="account-info">Loading...</p>
<script type="text/javascript">
function infoError() {
    $("#account-info").html('Failed to get account info.').css('color', 'red');
}

$.ajax('/account_info/', {
    dataType: 'json',
    success: function (data) {
      if (!data.success) {
          infoError();
          return;
      }

      var labels = ['available_balance', 'customer', 'identifier', 'email'];
      $("#account-info").html(labels.map(function (label) {
          var value = data.account[label];
          return '<b>' + label + ':</b> '
                 + (label == 'available_balance' ? '$' + value / 100 : value);
      }).join(', '));
    },
    error: infoError
})
</script>

<h2>Payments</h2>

<div class="table-responsive">
  <table class="table table-striped table-bordered" id="data-table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Receiver</th>
        <th>Method</th>
        <th class="text-right">Sum</th>
        <th class="text-right">State</th>
      </tr>
    </thead>
    <tbody>
      {% for payment in payments %}
        <tr>
          <td>{{ payment.created_on }}</td>
          <td>{{ payment.receiver.first_name }} {{ payment.receiver.last_name }}</td>
          <td>{{ payment.method }}</td>
          <td class="text-right">${{ payment.amount }}</td>
          <td class="text-right">{{ payment.get_state_display() }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/users/pay.j2
{% extends "base.j2" %}

{% block content %}
<h2>Pay {{ receiver.first_name}} {{ receiver.last_name }}</h2>

<div class="row">
    <div class="col-md-6">
        <form id="payment-form" class="form" role="form" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Issue a card" />
            </div>
        </form>
    </div>
    <div class="col-md-6" style="padding-top: 1.75em">
        <table class="table table-striped table-bordered">
        <tbody>
            <tr><td>First name</td><td>{{ receiver.first_name }}</td></tr>
            <tr><td>Last name</td><td>{{ receiver.last_name }}</td></tr>
            <tr><td>Email</td><td>{{ receiver.email }}</td></tr>
        </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/users/redeem.j2
{% extends "base.j2" %}

{% block content %}
{% if not active and last_payment and last_payment.failed %}
    <div class="alert alert-danger">
        <p>For whatever reason we failed to issue a Tango Card for you, this could be some temporary malfunction, so please try once more in a few minutes. In case that doesn't help please contact us.</p>
        <p>We are sorry for this inconvinience.</p>
    </div>
{% endif %}

<h2>Redeem</h2>

{% if active %}
    <p>Ordering Tango Card for you right now. Wait a bit and check your email.</p>
{% else %}

    <p>You have earned <b>${{ stats.unpayed }}</b> reward.
       You can either redeem it or donate your effort.
    </p>

    {% if stats.unpayed %}
        <form class="form" method="post">
            {% csrf_token %}
            <button name="redeem" type="submit" class="btn btn-primary">Redeem</button>
            <button name="donate" type="submit" class="btn btn-primary">Donate</button>
        </form>
    {% else %}
        <p>Nothing to redeem now.</p>
    {% endif %}
{% endif %}

{% endblock %}

templates/users/stats.j2
{% extends "base.j2" %}

{% block content %}
<h2>User statistics</h2>

<div class="table-responsive">
  <table class="table table-striped" id="data-table">
    <thead>
      <tr>
        <th>Name</th>
        <th class="text-right">Series validated</th>
        <th class="text-right">Concordant</th>
        <th class="text-right">Concordancy %</th>
        <th class="text-right">Samples validated</th>
        <th class="text-right">Earned annotations</th>
        <th class="text-right">Earned validations</th>
        <th class="text-right">Sum</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.first_name }} {{ user.last_name }}</td>
          <td class="text-right">{{ user.stats.serie_validations }}</td>
          <td class="text-right">{{ user.stats.serie_validations_concordant }}</td>
          <td class="text-right">{{ '{:.0f}%'.format(user.stats.serie_validation_concordancy * 100) if user.stats.serie_validation_concordancy else '-' }}</td>
          <td class="text-right">{{ user.stats.sample_validations }}</td>
          <td class="text-right">{{ user.stats.earned_sample_annotations }}</td>
          <td class="text-right">{{ user.stats.earned_sample_validations }}</td>
          <td class="text-right">${{ user.stats.unpayed }}</td>
          <td>
            {% if user.stats.unpayed %}
              <a href="{{ url('pay') }}?user_id={{ user.id }}" class="btn btn-primary btn-xs">Pay</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}